services:

  server:
    image: "tm-assignment"
    build:
      context: ./api
    container_name: tm-assignment
    depends_on:
      - db
    ports:
      - "8084:8084"
  db:
    image: postgres
    container_name: tm-postgres
    #  restart: always
    environment:
      - POSTGRES_DB=tm-postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - PGPORT=5450
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    expose:
      - "5450"
    ports:
      - "5450:5450"
  web:
    image: "web"
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      PORT: 3000
