server:
  port: 8084
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5450/tm-postgres
    password: password
    username: username
jwt:
  secret: "secret"
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true